baseURL = "https://waziup.org"
languageCode = "en-us"
title = "WAZIUP e.V"
theme = "hyperion"
publishDir = "public"
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-117557016-2"


[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    post = "/news/:title/"

[[menu.main]]
    name = "home"
    weight = -10
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "program"
    identifier = "program"
    weight = -9
    url = "/program/"
[[menu.main]]
    name = "ecosystem"
    identifier = "ecosystem"
    weight = -9
    url = "/ecosystem/"    
[[menu.main]]
    name = "use cases"
    identifier = "use_cases"
    weight = -8
    url = "/use_cases/"
[[menu.main]]
    name = "technology"
    identifier = "technology"
    weight = -7
    url = "http://www.waziup.io"    
[[menu.main]]
    name = "news & blog"
    identifier = "newsroom"
    weight = -6
    url = "/news/"    
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = -2
    url = "/contact/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = -9
    url = "/about/"    
   
    