baseURL = "https://waziup.org"
languageCode = "en-us"
title = "WAZIUP e.V"
theme = "hyperion"
publishDir = "public"
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-117557016-2"


[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    post = "/news/:title/"

[[menu.main]]
    name = "home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 2
    url = "https://www.wazihub.com"    
[[menu.main]]
    name = "services"
    identifier = "services"
    weight = 3
    url = "/"
[[menu.main]]
    name = "technology"
    identifier = "technology"
    weight = 4
    url = "http://www.waziup.io"    
[[menu.main]]
    name = "news & blog"
    identifier = "newsroom"
    weight = 5
    url = "https://wazihub.com/news/"    
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 5
    url = "/contact/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 7
    url = "/about/"    
[[menu.main]]
    name = "nodes"
    identifier = "nodes"
    weight = 8
    url = "/about/"    
   
    